# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(509, 266)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.win_label = QtWidgets.QLabel(self.centralwidget)
        self.win_label.setGeometry(QtCore.QRect(230, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.win_label.setFont(font)
        self.win_label.setObjectName("win_label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 80, 351, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.login_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.login_layout.setContentsMargins(0, 0, 0, 0)
        self.login_layout.setObjectName("login_layout")
        self.username_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.username_lbl.setObjectName("username_lbl")
        self.login_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_lbl)
        self.password_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.password_lbl.setObjectName("password_lbl")
        self.login_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_lbl)
        self.username_txt = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_txt.setObjectName("username_txt")
        self.login_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_txt)
        self.password_txt = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_txt.setObjectName("password_txt")
        self.login_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_txt)
        self.loginbtn = QtWidgets.QCommandLinkButton(self.formLayoutWidget)
        self.loginbtn.setObjectName("loginbtn")
        self.login_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loginbtn)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.win_label.setText(_translate("LoginWindow", "Login"))
        self.username_lbl.setText(_translate("LoginWindow", "Username :"))
        self.password_lbl.setText(_translate("LoginWindow", "Password :"))
        self.loginbtn.setText(_translate("LoginWindow", "Login "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
