# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserPanel(object):
    def setupUi(self, UserPanel):
        UserPanel.setObjectName("UserPanel")
        UserPanel.resize(509, 229)
        self.centralwidget = QtWidgets.QWidget(UserPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 50, 251, 87))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.logged_as = QtWidgets.QLabel(self.widget)
        self.logged_as.setObjectName("logged_as")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.logged_as)
        self.username_lbl = QtWidgets.QLabel(self.widget)
        self.username_lbl.setText("")
        self.username_lbl.setObjectName("username_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_lbl)
        self.logout_btn = QtWidgets.QPushButton(self.widget)
        self.logout_btn.setObjectName("logout_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.logout_btn)
        self.userinfo_btn = QtWidgets.QPushButton(self.widget)
        self.userinfo_btn.setObjectName("userinfo_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userinfo_btn)
        UserPanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserPanel)
        QtCore.QMetaObject.connectSlotsByName(UserPanel)

    def retranslateUi(self, UserPanel):
        _translate = QtCore.QCoreApplication.translate
        UserPanel.setWindowTitle(_translate("UserPanel", "MainWindow"))
        self.logged_as.setText(_translate("UserPanel", "Logged as :"))
        self.logout_btn.setText(_translate("UserPanel", "Logout"))
        self.userinfo_btn.setText(_translate("UserPanel", "User Info..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserPanel = QtWidgets.QMainWindow()
    ui = Ui_UserPanel()
    ui.setupUi(UserPanel)
    UserPanel.show()
    sys.exit(app.exec_())
