# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usermanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserManager(object):
    def setupUi(self, UserManager):
        UserManager.setObjectName("UserManager")
        UserManager.resize(510, 258)
        self.centralwidget = QtWidgets.QWidget(UserManager)
        self.centralwidget.setObjectName("centralwidget")
        self.app_label = QtWidgets.QLabel(self.centralwidget)
        self.app_label.setGeometry(QtCore.QRect(180, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.app_label.setFont(font)
        self.app_label.setObjectName("app_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 60, 101, 119))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginbtn = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.loginbtn.setObjectName("loginbtn")
        self.verticalLayout.addWidget(self.loginbtn)
        self.registerbtn = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.registerbtn.setObjectName("registerbtn")
        self.verticalLayout.addWidget(self.registerbtn)
        self.exitbtn = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.exitbtn.setObjectName("exitbtn")
        self.verticalLayout.addWidget(self.exitbtn)
        self.version_lbl = QtWidgets.QLabel(self.centralwidget)
        self.version_lbl.setGeometry(QtCore.QRect(380, 240, 67, 17))
        self.version_lbl.setObjectName("version_lbl")
        self.version_number = QtWidgets.QLabel(self.centralwidget)
        self.version_number.setGeometry(QtCore.QRect(450, 240, 51, 16))
        self.version_number.setText("")
        self.version_number.setObjectName("version_number")
        UserManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserManager)
        QtCore.QMetaObject.connectSlotsByName(UserManager)

    def retranslateUi(self, UserManager):
        _translate = QtCore.QCoreApplication.translate
        UserManager.setWindowTitle(_translate("UserManager", "MainWindow"))
        self.app_label.setText(_translate("UserManager", "User Manager"))
        self.loginbtn.setText(_translate("UserManager", "Login"))
        self.registerbtn.setText(_translate("UserManager", "Register"))
        self.exitbtn.setText(_translate("UserManager", "Exit"))
        self.version_lbl.setText(_translate("UserManager", "Version :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserManager = QtWidgets.QMainWindow()
    ui = Ui_UserManager()
    ui.setupUi(UserManager)
    UserManager.show()
    sys.exit(app.exec_())
